Importing dataset into file

In [17]:
import pandas as pd
from IPython.display import clear_output
for i in range(10):
    clear_output()

Importing the uncleaned/internship dataset from Evans Jobs

In [94]:
df = pd.read_excel('Initial_Dataset_through_6.19.2019.xls')

df = df[df['Flags'].str.contains("Entering Class of Fall 2018")]

#df['Agency/Organization Name'].unique()

df.drop(['Student'], axis = 1, inplace = True)

unpaid = len(df[df['Paid/Unpaid'].str.contains("No", na = False )])/len(df)

unpaid = round(unpaid*100, 2)

length = len(df)

print("Unpaid internships currently make up {}%".format(unpaid), "of internships taken by the Entering Class of 2018")

print("Currently, there are", length, " students who have completed the internship form")

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Unpaid internships currently make up 19.61% of internships taken by the Entering Class of 2018
Currently, there are 51 of students who have completed the internship form

In [97]:
df.head(10)

,Agency/Organization Name,Employer New,Date you began work,Date work ends,New Job Title,Compensation,Paid/Unpaid,City,State,Country,...,Are you an international student?,Would consider hiring this particular intern for a position in your agency?,Total Hours,Verify the total number of hours worked by intern,How did you find this internship?,Please explain.,Flags,Compensation Type,Expected Date of Graduation,Rate of Pay
0,City of Bellevue,NaN,2019-09-01,2020-06-01,Human Services Intern,NaN,Yes,Bellevue,Washington,United States,...,NaN,NaN,0,0,On-Campus Employer Recruiting Session,NaN,"*Concurrent Student, CURRENTLY ENROLLED, Enter...",NaN,NaT,NaN
1,NaN,Safe Place International,2019-07-01,2019-09-15,Operations Management Assistant Intern,NaN,No,Berkeley,California,United States,...,NaN,NaN,0,0,Previous Employment,NaN,"*Concurrent Student, CURRENTLY ENROLLED, Enter...",NaN,NaT,NaN
2,Washington State Auditor's Office,NaN,2019-07-01,2019-09-20,Performance Audit Intern,NaN,Yes,Olympia,Washington,United States,...,NaN,NaN,0,0,Alumni,NaN,"CURRENTLY ENROLLED, Entering Class of Fall 201...",NaN,NaT,NaN
3,Seattle Children's Hospital,NaN,2019-07-01,2019-09-23,Transportation Intern,NaN,Yes,Seattle,Washington,United States,...,NaN,NaN,0,0,EvansJobs/Career Development Office,NaN,"*Concurrent Student, CURRENTLY ENROLLED, Enter...",NaN,NaT,NaN
4,"City of Seattle, Finance and Administrative Se...",NaN,2019-06-26,2019-09-18,Policy Intern,NaN,Yes,Seattle,Washington,United States,...,NaN,NaN,0,0,Previous Contacts,NaN,"Career Institute Attendee 2018, Career Institu...",NaN,NaT,NaN
5,"City of Seattle, Seattle City Light",NaN,2019-06-26,2020-06-01,Planning Intern,NaN,Yes,Seattle,Washington,United States,...,NaN,NaN,0,0,Web Search,NaN,"CURRENTLY ENROLLED, Entering Class of Fall 201...",NaN,NaT,NaN
6,"City of Seattle, Seattle City Light",NaN,2019-06-26,2020-05-29,Natural Resources and Greenhouse Gas Program I...,NaN,Yes,Seattle,Washington,United States,...,NaN,NaN,0,0,Web Search,NaN,"CURRENTLY ENROLLED, Entering Class of Fall 201...",NaN,NaT,NaN
7,"City of Seattle, Department of Transportation ...",NaN,2019-06-26,2019-09-24,Public Space Management Intern,NaN,Yes,Seattle,Washington,United States,...,NaN,NaN,0,0,Web Search,NaN,"Career Institute Attendee 2018, CURRENTLY ENRO...",NaN,NaT,NaN
8,Equal Employment Opportunity Commission,NaN,2019-06-25,2019-09-27,Investigator,NaN,No,Seattle,Washington,United States,...,NaN,NaN,0,0,On-Campus Employer Recruiting Session,NaN,"CURRENTLY ENROLLED, Entering Class of Fall 201...",NaN,NaT,NaN
9,NaN,"UNESCO Phnom Penh Office, Cambodia",2019-06-24,2019-09-13,Intern,NaN,No,Phnom Penh,Non-U.S.,United States,...,NaN,NaN,0,0,Web Search,NaN,"*International Student, CURRENTLY ENROLLED, En...",NaN,NaT,NaN